"""Build the revised figures from supplied data, without generating new molecules.
Run: python build_figures.py  (requires matplotlib, numpy, Pillow, lxml, cairosvg, PyMuPDF)
No trained checkpoint, energy model, or external font file is required.
"""
from pathlib import Path
import base64,io,json,re,shutil,subprocess,copy
import numpy as np
from PIL import Image
from lxml import etree as E
import cairosvg
import fitz
ROOT=Path(__file__).resolve().parent
OUT=ROOT.parent/'figures';OUT.mkdir(exist_ok=True)
NS='http://www.w3.org/2000/svg'
INK='#233442';SUB='#536774';LINE='#d9e1e6';GEO='#29768b';PHY='#b56935'
METHOD_COLORS={'Gaussian FM':'#87939f','EDM':'#4479a3','GAGA':'#c18546','LatentSpring':'#197d78'}
METHOD_LINES={'Gaussian FM':':','EDM':'--','GAGA':'-.','LatentSpring':'-'}

def text(x,y,content,size=8.5,weight='normal',anchor='start',fill=INK):
    return f'<text x="{x}" y="{y}" font-family="DejaVu Sans" font-size="{size}" font-weight="{weight}" text-anchor="{anchor}" fill="{fill}">{content}</text>'

def math_svg(expression,x,y,size=9.0):
    from matplotlib.mathtext import math_to_image
    from matplotlib import rc_context
    from matplotlib.font_manager import FontProperties
    b=io.BytesIO()
    with rc_context({'mathtext.fontset':'dejavusans','svg.fonttype':'path'}):
        math_to_image('$'+expression+'$',b,prop=FontProperties(size=size),format='svg',color=INK)
    e=E.fromstring(b.getvalue())
    for g in e.xpath("//*[@id='patch_1']"):
        g.getparent().remove(g)
    w=float(e.attrib['width'].replace('pt',''));h=float(e.attrib['height'].replace('pt',''))
    e.attrib.update(dict(x=str(x),y=str(y),width=str(w),height=str(h)))
    # IDs generated by mathtext can repeat across independent equations.
    serial=f'm{int(x*100)}_{int(y*100)}_'
    raw=E.tostring(e).decode();ids=re.findall(r'id="([^"]+)"',raw)
    for i in ids:raw=raw.replace(f'id="{i}"',f'id="{serial+i}"').replace(f'#{i}"',f'#{serial+i}"').replace(f'#{i})',f'#{serial+i})')
    return raw

def img(path,x,y,w,h):
    b=base64.b64encode(Path(path).read_bytes()).decode()
    return f'<image x="{x}" y="{y}" width="{w}" height="{h}" href="data:image/png;base64,{b}"/>'

def rect(x,y,w,h,fill,stroke='none',rx=5):
    return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" fill="{fill}" stroke="{stroke}" stroke-width="0.6"/>'

def arrow(x1,y1,x2,y2):
    return f'<path d="M {x1} {y1} L {x2} {y2}" stroke="{SUB}" stroke-width="1.1" fill="none" marker-end="url(#arrow)"/>'

def export_svg(svg,path):
    path.write_text(svg)
    cairosvg.svg2pdf(url=str(path),write_to=str(path.with_suffix('.pdf')))
    # Rasterize the finished PDF: preview and publication PDF cannot drift.
    d=fitz.open(path.with_suffix('.pdf'));d[0].get_pixmap(matrix=fitz.Matrix(4,4),alpha=False).save(path.with_suffix('.png'))

def make_fig1():
    data=ROOT/'data';ims=[Image.open(data/(n+'_pymol.png')).convert('RGBA') for n in ['source','output']]
    boxes=[im.getbbox() for im in ims];x0=min(b[0] for b in boxes);y0=min(b[1] for b in boxes);x1=max(b[2] for b in boxes);y1=max(b[3] for b in boxes)
    pad=22;box=(max(0,x0-pad),max(0,y0-pad),min(ims[0].width,x1+pad),min(ims[0].height,y1+pad))
    for n,im in zip(['source','output'],ims):im.crop(box).save(data/(n+'_display.png'))
    w,h=box[2]-box[0],box[3]-box[1];dispw=112;disph=dispw*h/w
    s=[f'<svg xmlns="{NS}" xmlns:xlink="http://www.w3.org/1999/xlink" width="396pt" height="330pt" viewBox="0 0 396 330">',
       '<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5.5" markerHeight="5.5" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 Z" fill="'+SUB+'"/></marker></defs>',rect(0,0,396,330,'white',rx=0)]
    s += [text(4,14,'a',11,'bold'),text(20,14,'From composition to 3D structure',10.6,'bold'),text(20,30,'Atom identities · total charge · spin multiplicity',8.3,fill=SUB)]
    s += [text(60,52,'Harmonic source',9.1,'bold','middle'),text(336,52,'Raw output',9.1,'bold','middle')]
    s += [img(data/'source_display.png',4,61,112,disph),img(data/'output_display.png',280,61,112,disph)]
    s += [rect(138,70,120,46,'#eef4f6',LINE),text(198,87,'LatentSpring flow',9.4,'bold','middle'),text(198,103,'EGNN + corrections',8.5,anchor='middle',fill=SUB),arrow(117,92,134,92),arrow(262,92,278,92)]
    s += [math_svg(r'X_0\sim q_0(\cdot\mid c)',29,140,9),math_svg(r'X_{\mathrm{gen}}\in\mathbb{R}^{23\times3}',291,140,9)]
    s += [text(60,163,'Auxiliary edges only',8.1,anchor='middle',fill=SUB),text(198,134,'Neural sampling',8.2,anchor='middle',fill=SUB),text(336,163,'C₇H₁₅N · neutral singlet',8.1,anchor='middle',fill=SUB)]
    s += [f'<line x1="4" x2="392" y1="178" y2="178" stroke="{LINE}" stroke-width=".7"/>',text(4,196,'b',11,'bold'),text(20,196,'Correct the predicted endpoint',10.6,'bold')]
    # Three aligned cards make the sequential conditioning explicit.
    s += [rect(4,207,118,52,'#edf6f8',LINE),rect(140,207,118,52,'#fcf3ec',LINE),rect(276,207,116,52,'#f3f5f7',LINE)]
    s += [text(63,223,'Geometry',9.3,'bold','middle',GEO),math_svg(r'g=G_\psi(H,p;c)',28,232,9.2),
          text(199,223,'Physics',9.3,'bold','middle',PHY),math_svg(r'f=A_\phi(X,H_g,p;c)',150,232,9.2),
          text(334,223,'Endpoint update',9.3,'bold','middle'),math_svg(r'\Delta H=(1-p)(g+\eta f)',282,232,9.0),
          arrow(124,231,138,231),arrow(260,231,274,231),math_svg(r'H_g=H+(1-p)g',13,264,8.7),text(199,274,'Force-based supervision',8.1,anchor='middle',fill=SUB),text(334,274,'Flow or diffusion',8.1,anchor='middle',fill=SUB)]
    s += [f'<line x1="4" x2="392" y1="288" y2="288" stroke="{LINE}" stroke-width=".7"/>',
          text(4,303,'Training',8.5,'bold'),text(53,303,'Reference geometry → backbone + geometry head',8.15,fill=GEO),
          text(53,317,'eSEN force targets → physical head',8.15,fill=PHY)]
    s.append('</svg>');export_svg(''.join(s),OUT/'figure1.svg')
    (OUT/'figure1_provenance.json').write_text(json.dumps({'scene_file':'figure_source/data/scenes.json','render_assets':'supplied PyMOL 3.1.0 renders, not rerun in this environment','shared_crop':box,'same_camera_and_scale':True,'coordinates_modified':False,'new_bonds_inferred_for_drawing':False,'source_edges':'actual replayed auxiliary tree','sample_scope':'12-composition common-element organic validation panel; not the 64-composition main panel','equation_eta':4},indent=2))

def make_fig2():
    # Each plot is authored independently; two vector plots are then assembled.
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from matplotlib.patches import Patch
    plt.rcParams.update({'font.family':'DejaVu Sans','font.size':8.5,'axes.labelsize':8.5,'xtick.labelsize':8,'ytick.labelsize':8.5,'pdf.fonttype':42,'svg.fonttype':'none'})
    series=json.loads((ROOT/'data/figure2_plot_data.json').read_text())
    paneldir=ROOT/'panels';paneldir.mkdir(exist_ok=True)
    fig=plt.figure(figsize=(3.10,2.72));ax=fig.add_axes([.33,.24,.65,.63]);ax.spines[['top','right','left']].set_visible(False)
    for i,row in enumerate(series):
        y=(3-i)*2.8
        bars=ax.barh([y+.43,y-.43],[row['graph'],row['graph_force']],height=.68,color=METHOD_COLORS[row['method']])
        bars[0].set_alpha(.28)
        for p,val in zip(bars,[row['graph'],row['graph_force']]):
            ax.text(val+.75,p.get_y()+p.get_height()/2,f'{val:.2f}',fontsize=8,va='center')
    ax.set_yticks([i*2.8 for i in range(4)],[r['method'] for r in series[::-1]])
    ax.set_xlim(0,46);ax.set_ylim(-1.25,9.8);ax.set_xticks([0,20,40]);ax.tick_params(axis='y',length=0,pad=5)
    ax.grid(axis='x',alpha=.18,linewidth=.5);ax.set_axisbelow(True);ax.set_xlabel('All generation attempts (%)',labelpad=5)
    fig.text(.03,.947,'a  Graph and force',fontsize=10,fontweight='bold')
    # Two independent legend samples encode opacity rather than a new data series.


    for ext in ['svg','pdf']:fig.savefig(paneldir/('main_left.'+ext))
    plt.close(fig)
    fig=plt.figure(figsize=(2.40,2.72));ax=fig.add_axes([.27,.24,.68,.63]);ax.spines[['top','right']].set_visible(False)
    for row in series:
        ax.step(row['threshold'],row['curve'],where='post',linewidth=1.3 if row['method']!='LatentSpring' else 1.8,color=METHOD_COLORS[row['method']],linestyle=METHOD_LINES[row['method']])
    ax.axvline(5,linestyle=':',linewidth=.8,alpha=.6,color='#87939f')
    ax.set_xlim(0,10);ax.set_ylim(0,12);ax.set_xticks([0,5,10]);ax.set_yticks([0,4,8,12]);ax.grid(axis='y',alpha=.18,linewidth=.5);ax.set_axisbelow(True)
    ax.set_xlabel('Force threshold (eV/Å)',labelpad=5);ax.set_ylabel('Geometry-and-force yield (%)',labelpad=5)
    fig.text(.04,.947,'b  Local geometry',fontsize=10,fontweight='bold')


    for ext in ['svg','pdf']:fig.savefig(paneldir/('main_right.'+ext))
    plt.close(fig)
    # SVG assembly preserves native 8–10 pt text and vector curves.
    roots=[]
    for index,name in enumerate(['main_left','main_right']):
        node=E.parse(str(paneldir/(name+'.svg'))).getroot();raw=E.tostring(node).decode()
        ids=re.findall(r'id="([^"]+)"',raw)
        for ident in ids:raw=raw.replace(f'id="{ident}"',f'id="p{index}_{ident}"').replace(f'#{ident}"',f'#p{index}_{ident}"').replace(f'#{ident})',f'#p{index}_{ident})')
        node=E.fromstring(raw.encode());node.attrib.update(dict(x=str(index*223.2),y='0',width=str([223.2,172.8][index]),height='195.84'));roots.append(E.tostring(node).decode())
    svg=f'<svg xmlns="{NS}" width="396pt" height="206pt" viewBox="0 0 396 206">'+''.join(roots)+'<rect x="42" y="191" width="14" height="6" fill="'+INK+'" opacity=".28"/>'+text(61,197,'Graph-valid',8.2)+rect(162,191,14,6,INK,rx=0)+text(181,197,'Graph-valid + force ≤ 5 eV/Å',8.2)+'</svg>'
    export_svg(svg,OUT/'main_comparison.svg')

if __name__=='__main__':
    make_fig1();make_fig2()
    manuscript_figures=ROOT.parent/'manuscript/figures'
    if manuscript_figures.is_dir():
        for p in OUT.glob('*.pdf'):shutil.copyfile(p,manuscript_figures/p.name)
    print('Rebuilt Fig1 and Fig2 from supplied records and checked data.')
