#!/usr/bin/env bash
# =====================================================================
#  fig1_build.sh --- build + verify Figure 1 (conceptual, TikZ, no data)
#
#  Figure 1 is pure TikZ and is \input directly into main.tex, so the
#  paper build does NOT need the PDF this script produces.  The PDF/PNG
#  in figures/out/ exist for two reasons only:
#     1. proof that the figure compiles and does not collide with itself
#        (open figures/out/fig1_objective.png and look at it);
#     2. a fallback \includegraphics target if a future main.tex drops
#        \usepackage{tikz}.
#
#  STAGE 2 (added in the C8 pass) compiles the float inside the REAL
#  ICLR preamble.  This is not redundant with stage 1: the standalone
#  bootstrap uses plain article+times, whose metrics are slightly
#  narrower than iclr2027_conference.sty's, so a node can fit standalone
#  and still wrap in the paper.  Two real collisions in the shipped
#  main.pdf were invisible to stage 1 and caught only here.  Stage 2
#  needs iclr2027_conference.sty and math_commands.tex, so it is skipped
#  (with a message, not an error) if they are absent.
#
#  Usage:  bash figures/fig1_build.sh        (run from paper/ or anywhere)
# =====================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/out"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

mkdir -p "$OUT"
cp "$HERE/fig1_objective.tex" "$TMP/"

cd "$TMP"
pdflatex -interaction=nonstopmode -halt-on-error fig1_objective.tex > build.log 2>&1 || {
    echo "FAILED -- last 40 lines of pdflatex log:"; tail -40 build.log; exit 1; }

# Overfull/underfull boxes indicate text that has escaped its node width.
if grep -q "Overfull" build.log; then
    echo "WARNING: overfull boxes (text wider than its node):"
    grep -n "Overfull" build.log
fi

cp fig1_objective.pdf "$OUT/fig1_objective.pdf"
pdftoppm -r 300 -png -singlefile fig1_objective.pdf "$OUT/fig1_objective"

echo "wrote $OUT/fig1_objective.pdf"
echo "wrote $OUT/fig1_objective.png"
pdfinfo "$OUT/fig1_objective.pdf" | grep -E "Page size|Pages"

# ---------------------------------------------------------------- stage 2
PAPER="$(cd "$HERE/.." && pwd)"
if [[ ! -f "$PAPER/iclr2027_conference.sty" || ! -f "$PAPER/math_commands.tex" ]]; then
    echo "stage 2 skipped: iclr2027_conference.sty / math_commands.tex not found"
    exit 0
fi

cat > "$PAPER/fig1check.tex" <<'EOF'
% AUTO-GENERATED by figures/fig1_build.sh -- in-column render check for
% Figure 1.  Safe to delete; the script rewrites and removes it.
\documentclass{article}
\usepackage{iclr2027_conference,times}
\usepackage{amsmath,amssymb,amsthm}
\let\amseqref\eqref
\input{math_commands.tex}
\let\eqref\amseqref
\usepackage{graphicx}\usepackage{booktabs}\usepackage{array}\usepackage{xcolor}
\usepackage{subcaption}\usepackage{microtype}\usepackage{tikz}
\captionsetup{font=small,skip=5pt}
\begin{document}
\input{figures/fig1_objective_float}
\noindent Body text placeholder so the float has a page to sit on.
\end{document}
EOF

cd "$PAPER"
if pdflatex -interaction=nonstopmode -halt-on-error fig1check.tex > fig1check.buildlog 2>&1; then
    if grep -qE "Overfull|Underfull" fig1check.buildlog; then
        echo "STAGE 2 WARNING: bad boxes under the ICLR preamble:"
        grep -E "Overfull|Underfull" fig1check.buildlog
    else
        echo "stage 2 OK: no bad boxes under the ICLR preamble"
    fi
    pdftoppm -r 300 -png -singlefile fig1check.pdf "$OUT/fig1_objective_incolumn"
    echo "wrote $OUT/fig1_objective_incolumn.png  (LOOK AT IT: stage 1 cannot see wrap)"
else
    echo "STAGE 2 FAILED -- last 30 lines:"; tail -30 fig1check.buildlog
fi
rm -f "$PAPER"/fig1check.tex "$PAPER"/fig1check.aux "$PAPER"/fig1check.log \
      "$PAPER"/fig1check.out "$PAPER"/fig1check.pdf "$PAPER"/fig1check.buildlog
