"""Fixed-schedule tempered SMC with exact Metropolis proposal correction.

Standard SMC/AIS and MALA/RWM building blocks, not new algorithms. An explicitly
normalized Gaussian mixture may use centers generated by a frozen FM pilot;
the pilot must be independent of the subsequent population. Its density is
the finite mixture density, not an approximation claimed as the FM likelihood.
All states use Euclidean (e.g. intrinsic COM-free) coordinates, one condition
per population. Oracle calls must be independent across rows.
"""
from dataclasses import dataclass
import math
from typing import Callable

import torch
from torch import Tensor

from cfm_mol.nonequilibrium import _schedule, _states, gaussian_log_density, normalized_weights


@dataclass
class DensityValue:
    log_value: Tensor
    score: Tensor | None = None

    def validate(self, x: Tensor, need_score: bool) -> 'DensityValue':
        if self.log_value.shape != (len(x),) or not torch.isfinite(self.log_value).all():
            raise ValueError('Density must return one finite log value per particle')
        if need_score and (self.score is None or self.score.shape != x.shape or not torch.isfinite(self.score).all()):
            raise ValueError('MALA needs a finite score for every coordinate')
        return self

    def take(self, indices: Tensor) -> 'DensityValue':
        return DensityValue(self.log_value[indices], None if self.score is None else self.score[indices])


class IsotropicGaussianMixture:
    """Fixed, normalized, equal-weight Gaussian mixture and its analytic score."""
    def __init__(self, centers: Tensor, std: float):
        _states(centers)
        if not math.isfinite(std) or std <= 0:raise ValueError('Mixture std must be positive')
        self.centers=centers.detach().double().clone();self.std=std

    def sample(self, n: int, generator: torch.Generator) -> tuple[Tensor, Tensor]:
        if n<1:raise ValueError('Require positive sample count')
        labels=torch.randint(len(self.centers),(n,),device=self.centers.device,generator=generator)
        noise=torch.randn((n,self.centers.shape[1]),dtype=self.centers.dtype,device=self.centers.device,generator=generator)
        return self.centers[labels]+self.std*noise,labels

    def __call__(self, x: Tensor) -> DensityValue:
        residual=(x.double()[:,None,:]-self.centers[None,:,:])/self.std
        log_components=-.5*residual.square().sum(-1)-x.shape[-1]*math.log(self.std*math.sqrt(2*math.pi))
        log_value=torch.logsumexp(log_components,dim=-1)-math.log(len(self.centers))
        score=-(torch.softmax(log_components,dim=-1)[:,:,None]*residual).sum(1)/self.std
        return DensityValue(log_value,score)


@dataclass
class TemperedPopulation:
    positions: Tensor
    log_weights: Tensor  # normalized; after resampling these are not path works
    log_normalizer_estimate: float
    ancestors: Tensor
    history: list[dict]
    target_evaluations: int
    target_log_values: Tensor
    last_global_proposal: Tensor | None = None

    def summary(self) -> dict:
        w=normalized_weights(self.log_weights)
        ancestry_mass=torch.zeros(len(w),dtype=w.dtype,device=w.device).scatter_add_(0,self.ancestors,w)
        result={'particles':len(w),'ess':float(1/w.square().sum()),
            'ess_fraction':float(1/(len(w)*w.square().sum())), 'maximum_weight':float(w.max()),
            'distinct_initial_ancestors':int(torch.unique(self.ancestors).numel()),
            'ancestral_ess':float(1/ancestry_mass.square().sum()),
            'log_normalizer_estimate':self.log_normalizer_estimate,
            'target_evaluations':self.target_evaluations,
            'resampling_events':sum(row['resampled'] for row in self.history),
            'scope':'weighted SMC population; endpoint ESS alone does not measure diversity or independence'}
        if self.last_global_proposal is not None:
            observed=self.last_global_proposal[self.last_global_proposal>=0]
            result.update(distinct_last_accepted_global_proposals=int(torch.unique(observed).numel()),
                global_replacement_weight_mass=float(w@(self.last_global_proposal>=0).double()),
                global_proposal_scope='accepted proposal IDs track refresh events, not independent effective samples')
        return result


def _clip_score(score: Tensor, max_norm: float) -> Tensor:
    norm=score.norm(dim=-1,keepdim=True)
    return score*torch.clamp(max_norm/norm.clamp_min(torch.finfo(score.dtype).tiny),max=1)


def metropolis_log_acceptance(current: Tensor, proposed: Tensor, log_current: Tensor,
                             log_proposed: Tensor, mean_forward: Tensor,
                             mean_reverse: Tensor, std: float) -> Tensor:
    """The Gaussian reverse proposal is essential even for a learned/clipped drift."""
    return (log_proposed.double()-log_current.double()
        +gaussian_log_density(current,mean_reverse,std)-gaussian_log_density(proposed,mean_forward,std))


@torch.no_grad()
def tempered_smc(x0: Tensor, initial: Callable[[Tensor], DensityValue],
                 target: Callable[[Tensor], DensityValue], betas, *,
                 proposal_std: float, generator: torch.Generator,
                 kernel: str = 'mala', moves_per_stage: int = 1,
                 resample_threshold: float = .5, max_score_norm: float = 100.,
                 callback: Callable[[dict],None] | None = None, hmc_leapfrog_steps: int = 8,
                 hmc_step_size_schedule: Callable[[float],float] | None = None) -> TemperedPopulation:
    """Geometric bridges, pre-move reweighting, optional resampling, MH moves.

    With a fixed schedule, a normalized initial density, iid x0 from that
    density and the support/integrability conditions, standard SMC gives an
    unbiased *normalizer* estimator. Its log and self-normalized expectations
    have finite-particle bias. Repeated descendants are explicitly tracked.
    'hybrid' alternates an independence-MH proposal from the fixed initial
    density with local MALA; it requires two moves per stage. 'independence'
    uses only global proposals. Initial ancestry remains an origin diagnostic,
    not a measure of decorrelation after MCMC. No online kernel tuning or
    adaptive temperature selection is hidden in this implementation.
    """
    _states(x0);grid=_schedule(betas,'betas')
    if kernel not in ['mala','rwm','independence','hybrid','hmc']:raise ValueError('Unknown MH kernel')
    if not math.isfinite(proposal_std) or proposal_std<=0 or not isinstance(moves_per_stage,int) or moves_per_stage<1:
        raise ValueError('Invalid MH step or move count')
    if not 0<=resample_threshold<=1 or not math.isfinite(max_score_norm) or max_score_norm<=0:
        raise ValueError('Invalid resampling threshold or score cap')
    if kernel=='hmc' and (not isinstance(hmc_leapfrog_steps,int) or hmc_leapfrog_steps<1):raise ValueError('Positive HMC trajectory length required')
    if kernel=='hybrid' and moves_per_stage!=2:raise ValueError('Hybrid requires exactly two moves per stage')
    if kernel in ['hybrid','independence'] and not callable(getattr(initial,'sample',None)):
        raise ValueError('Global MH requires a sampler for the exact initial density')
    x=x0.detach().double().clone();n=len(x);need_score=kernel in ['mala','hybrid','hmc']
    a=initial(x).validate(x,need_score);b=target(x).validate(x,need_score)
    logw=x.new_full((n,),-math.log(n));logz=0.;ancestors=torch.arange(n,device=x.device)
    history=[];target_evaluations=n
    global_ids=torch.full((n,),-1,dtype=torch.long,device=x.device)
    for stage,(previous,beta) in enumerate(zip(grid,grid[1:])):
        proposed_weights=logw+(beta-previous)*(b.log_value.double()-a.log_value.double())
        increment=torch.logsumexp(proposed_weights,0)
        logz+=float(increment);logw=proposed_weights-increment
        w=normalized_weights(logw);ess=float(1/w.square().sum())
        resampled=ess<resample_threshold*n
        if resampled:
            indices=torch.multinomial(w,n,replacement=True,generator=generator)
            x=x[indices];a=a.take(indices);b=b.take(indices);ancestors=ancestors[indices]
            global_ids=global_ids[indices]
            logw=x.new_full((n,),-math.log(n))
        accept_count=0;global_accepted=0;global_attempted=0
        for move in range(moves_per_stage):
            if kernel=='hmc':
                from cfm_mol.fixed_target_mcmc import hmc_population
                def bridge(z):
                    pa=initial(z).validate(z,True);pb=target(z).validate(z,True)
                    return DensityValue((1-beta)*pa.log_value+beta*pb.log_value,
                        (1-beta)*pa.score+beta*pb.score)
                cached=DensityValue((1-beta)*a.log_value+beta*b.log_value,(1-beta)*a.score+beta*b.score)
                scale=proposal_std if hmc_step_size_schedule is None else hmc_step_size_schedule(beta)
                x,mixed,stats=hmc_population(x,bridge,leapfrog_counts=[hmc_leapfrog_steps],
                    step_size=scale,generator=generator,max_score_norm=max_score_norm,initial_value=cached)
                target_evaluations+=stats['target_evaluations']
                accept_count+=sum(stats['accepted_per_chain'])
                a=initial(x).validate(x,True)
                # beta>0 on every mutation stage. Recover the accepted target
                # value/score from the returned bridge, avoiding a repeated oracle
                # query. Double precision and shifted energies limit cancellation.
                b=DensityValue((mixed.log_value-(1-beta)*a.log_value)/beta,
                    (mixed.score-(1-beta)*a.score)/beta).validate(x,True)
                continue
            global_move=kernel=='independence' or (kernel=='hybrid' and move==0)
            mean=x
            if need_score and not global_move:
                score=(1-beta)*a.score.double()+beta*b.score.double()
                mean=x+.5*proposal_std**2*_clip_score(score,max_score_norm)
            if global_move:
                proposed,_=initial.sample(n,generator)
                if proposed.shape!=x.shape:raise ValueError('Global proposal shape changed')
                global_attempted+=n
            else:
                proposed=mean+proposal_std*torch.randn(x.shape,dtype=x.dtype,device=x.device,generator=generator)
            _states(proposed)
            pa=initial(proposed).validate(proposed,need_score);pb=target(proposed).validate(proposed,need_score)
            target_evaluations+=n
            reverse=proposed
            if need_score and not global_move:
                reverse_score=(1-beta)*pa.score.double()+beta*pb.score.double()
                reverse=proposed+.5*proposal_std**2*_clip_score(reverse_score,max_score_norm)
            if global_move:
                ratio=beta*((pb.log_value-pa.log_value)-(b.log_value-a.log_value))
            else:
                ratio=metropolis_log_acceptance(x,proposed,(1-beta)*a.log_value+beta*b.log_value,
                    (1-beta)*pa.log_value+beta*pb.log_value,mean,reverse,proposal_std)
            if not torch.isfinite(ratio).all():raise FloatingPointError('Non-finite MH ratio')
            accept=torch.rand(n,device=x.device,dtype=x.dtype,generator=generator).log()<ratio.clamp_max(0)
            if global_move:
                proposed_ids=torch.arange(n,device=x.device)+(stage*moves_per_stage+move)*n
                global_ids=torch.where(accept,proposed_ids,global_ids);global_accepted+=int(accept.sum())
            x=torch.where(accept[:,None],proposed,x)
            a=DensityValue(torch.where(accept,pa.log_value,a.log_value),
                None if not need_score else torch.where(accept[:,None],pa.score,a.score))
            b=DensityValue(torch.where(accept,pb.log_value,b.log_value),
                None if not need_score else torch.where(accept[:,None],pb.score,b.score))
            accept_count+=int(accept.sum())
        row={'stage':stage+1,'beta':beta,'ess_before_resampling':ess,'resampled':resampled,
             'distinct_initial_ancestors':int(torch.unique(ancestors).numel()),
             'acceptance_fraction':accept_count/(n*moves_per_stage),'target_evaluations':target_evaluations,
             'log_normalizer_estimate':logz}
        if global_attempted:
            row['global_acceptance_fraction']=global_accepted/global_attempted
            row['distinct_last_accepted_global_proposals']=int(torch.unique(global_ids[global_ids>=0]).numel())
        history.append(row)
        if callback is not None:callback(dict(row))
    return TemperedPopulation(x,logw,logz,ancestors,history,target_evaluations,b.log_value,
        global_ids if kernel in ['independence','hybrid'] else None)
